"""Assembler packaging canonical PyAutoStat exports into verifiable ZIP bundles."""

from __future__ import annotations

import io
import json
import zipfile
from collections.abc import Sequence
from typing import Any

from .. import __version__
from ..exceptions import ReportError
from ..research_report import ResearchReport
from ..results import AnalysisResult
from ..workflow import ResearchWorkflowResult
from .manifest import (
    BundleFileRecord,
    build_manifest_dict,
    compute_sha256,
    serialize_manifest,
)
from .models import (
    ALL_BUNDLE_FORMATS,
    BUNDLE_SCHEMA_VERSION,
    CANONICAL_FORMAT_ORDER,
    DEFAULT_BUNDLE_FORMATS,
    BundleOptions,
)
from .safety import sanitize_table_id, validate_zip_member_path


def normalize_requested_formats(formats: Sequence[str] | None) -> tuple[str, ...]:
    """Validate, deduplicate, and sort requested bundle formats canonically."""
    if formats is None:
        return DEFAULT_BUNDLE_FORMATS

    if not isinstance(formats, (list, tuple, set)) or len(formats) == 0:
        raise ReportError("At least one format must be requested for bundle export.")

    normalized: list[str] = []
    seen: set[str] = set()

    for item in formats:
        if not isinstance(item, str) or not item.strip():
            raise ReportError(f"Invalid bundle format identifier: {item!r}")
        fmt = item.strip().lower()
        if fmt not in ALL_BUNDLE_FORMATS:
            supported = ", ".join(repr(f) for f in ALL_BUNDLE_FORMATS)
            raise ReportError(
                f"Unsupported bundle format: '{fmt}'. Supported formats are: {supported}."
            )
        if fmt not in seen:
            seen.add(fmt)
            normalized.append(fmt)

    # Order according to CANONICAL_FORMAT_ORDER
    ordered = [f for f in CANONICAL_FORMAT_ORDER if f in seen]
    return tuple(ordered)


def _generate_readme_text(
    *,
    target_type: str,
    method_id: str | None,
    detail: str,
    style: str,
    declared_files: list[BundleFileRecord],
) -> str:
    """Generate deterministic, non-statistical documentation for the bundle."""
    file_lines: list[str] = []
    for f in sorted(declared_files, key=lambda x: x.path):
        file_lines.append(
            f"- `{f.path}` ({f.format.upper()}, {f.size_bytes:,} bytes, role: {f.role})"
        )
    files_manifest_md = "\n".join(file_lines) if file_lines else "None recorded."

    return f"""# PyAutoStat Research Export Bundle

This archive was generated by PyAutoStat version {__version__} adhering to bundle
schema version {BUNDLE_SCHEMA_VERSION}.
It packages canonical, integrity-verifiable research reports and provenance artifacts,
tabular exports, and machine-readable records.

## Bundle Metadata
- **Bundle Schema Version:** {BUNDLE_SCHEMA_VERSION}
- **PyAutoStat Version:** {__version__}
- **Target Type:** {target_type}
- **Statistical Method:** {method_id or "Not specified"}
- **Detail Mode:** {detail}
- **Style Mode:** {style}

## Archive Structure
```text
pyautostat_bundle/
    README.md
    manifest.json
    report/          # Human-readable and publication documents (HTML, PDF, DOCX, etc.)
    data/            # Machine-readable structured reports (JSON)
    tables/          # Canonical presentation tables (CSV)
    figures/         # Publication-quality static scientific figures (PNG, SVG, PDF)
    provenance/      # Execution records, audit trails, and reproducibility specs
```

## Included Artifacts
{files_manifest_md}

## Integrity & Verification
All member files, exact sizes, and SHA-256 cryptographic digests are recorded in
`pyautostat_bundle/manifest.json`.

To verify the integrity of this bundle against file corruption or tampering using PyAutoStat:

```python
from pyautostat import verify_bundle

result = verify_bundle("path/to/this_bundle.zip")
if result.valid:
    print("Bundle integrity verified successfully.")
else:
    print("Integrity verification failed:", result.errors)
```

> **Note on Verification:**
> SHA-256 checksums verify bundle file integrity against transmission errors,
> incomplete writes, or file modification.
> They do not constitute digital cryptographic signatures, identity certificates,
> or legal non-repudiation.

## Privacy & Source Data Notice
This research export bundle contains derived reporting artifacts, aggregate summary tables,
and recorded execution provenance.
**Raw dataset observations, participant identifiers, and raw data rows are not included
in this package.**
Sharing raw data is a separate workflow subject to independent data governance, participant
consent, and privacy regulations.
"""


class BundleAssembler:
    """Orchestrates in-memory generation of canonical artifacts and ZIP packaging."""

    def __init__(
        self,
        target: Any,
        *,
        formats: Sequence[str] | None = None,
        options: BundleOptions | None = None,
    ) -> None:
        self.target = target
        self.formats = normalize_requested_formats(formats)
        self.options = options or BundleOptions()

        # Resolve target structure
        self.report: ResearchReport | None = None
        self.analysis: AnalysisResult | None = None
        self.audit: Any = None
        self.reproducibility: Any = None
        self.session: Any = None
        self.view: Any = None

        if isinstance(target, ResearchWorkflowResult):
            self.target_type = "ResearchWorkflowResult"
            self.report = target.report
            self.analysis = target.analysis
            self.audit = target.audit
            self.reproducibility = target.reproducibility
        elif isinstance(target, ResearchReport):
            self.target_type = "ResearchReport"
            self.report = target
            self.analysis = getattr(target, "_source_result", None)
            self.audit = getattr(target, "_source_audit", None)
            self.reproducibility = getattr(target, "_source_reproducibility", None)
            self.session = getattr(target, "_source_session", None)
        elif isinstance(target, AnalysisResult):
            self.target_type = "AnalysisResult"
            self.analysis = target
        else:
            # Fallback for presentation objects (e.g. PresentationView)
            self.target_type = type(target).__name__
            self.view = target

        self._validate_target_compatibility()

    def _validate_target_compatibility(self) -> None:
        """Validate format support for the given target type."""
        for fmt in self.formats:
            if fmt in ("csv", "markdown", "latex") and self.report is None:
                raise ReportError(
                    f"Format '{fmt}' requires a ResearchReport or ResearchWorkflowResult target."
                )
            if self.target_type == "PresentationView":
                if fmt not in ("html", "pdf", "docx"):
                    raise ReportError(
                        f"Format '{fmt}' is not supported for PresentationView targets. "
                        "PresentationView only supports 'html', 'pdf', and 'docx'."
                    )

    def assemble(self) -> bytes:
        """Produce the complete in-memory ZIP bundle bytes."""
        file_records: list[BundleFileRecord] = []
        file_payloads: list[tuple[str, bytes]] = []
        generated_paths: set[str] = set()

        def add_file(path: str, role: str, fmt: str, payload: bytes) -> None:
            validate_zip_member_path(path)
            if path in generated_paths:
                raise ReportError(
                    f"Duplicate bundle member path generated: {path!r}. "
                    "Distinct artifacts cannot map to the same internal bundle path."
                )
            generated_paths.add(path)
            digest = compute_sha256(payload)
            record = BundleFileRecord(
                path=path,
                role=role,
                format=fmt,
                size_bytes=len(payload),
                sha256=digest,
            )
            file_records.append(record)
            file_payloads.append((path, payload))

        # 1. Generate human-readable & publication report formats (each format rendered once)
        self._assemble_report_formats(add_file)

        # 2. Tabular CSV exports
        if "csv" in self.formats and self.report is not None:
            csv_tables = self.report.to_csv_tables()
            for tid, csv_str in csv_tables.items():
                safe_id = sanitize_table_id(tid)
                csv_bytes = csv_str.encode("utf-8")
                path = f"pyautostat_bundle/tables/{safe_id}.csv"
                add_file(path, "tabular_export", "csv", csv_bytes)

        # 3. Provenance files (analysis, audit, reproducibility, session)
        self._assemble_provenance(add_file)

        # 4. Standalone static scientific figures
        if self.options.include_static_figures:
            from ..presentation.figures.api import to_static_figures

            fig_target = self.report if self.report is not None else (self.analysis or self.target)
            fig_artifacts = to_static_figures(
                fig_target,
                format=self.options.static_figure_format,
                detail=self.options.detail,
            )
            for art in fig_artifacts:
                fig_path = f"pyautostat_bundle/figures/{art.filename}"
                add_file(fig_path, "scientific_figure", art.format, art.data)

        # 5. Generate README.md
        method_id = getattr(self.analysis, "method_id", None)
        if method_id is None and self.report is not None:
            rep_payload = self.report.to_dict()
            method_id = (
                rep_payload.get("method_id")
                or rep_payload.get("metadata", {}).get("method_id")
                or rep_payload.get("sections", {}).get("results", {}).get("method_id")
            )

        readme_text = _generate_readme_text(
            target_type=self.target_type,
            method_id=method_id,
            detail=self.options.detail,
            style=self.options.style,
            declared_files=file_records,
        )
        readme_bytes = readme_text.encode("utf-8")
        add_file("pyautostat_bundle/README.md", "documentation", "markdown", readme_bytes)

        # 6. Build and serialize manifest.json
        report_status = "complete"
        if self.report is not None:
            report_status = str(self.report.status)
        elif self.analysis is not None:
            report_status = str(self.analysis.status.value)

        manifest_dict = build_manifest_dict(
            target_type=self.target_type,
            report_status=report_status,
            method_id=method_id,
            detail=self.options.detail,
            style=self.options.style,
            include_figures=self.options.include_figures,
            include_static_figures=self.options.include_static_figures,
            files=file_records,
        )
        manifest_bytes = serialize_manifest(manifest_dict)
        validate_zip_member_path("pyautostat_bundle/manifest.json")
        file_payloads.append(("pyautostat_bundle/manifest.json", manifest_bytes))

        # 6. Assemble in-memory ZIP package with deterministic member order
        zip_buf = io.BytesIO()
        with zipfile.ZipFile(zip_buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
            # Manifest and README first, then alphabetically sorted members
            priority = {"pyautostat_bundle/README.md": 0, "pyautostat_bundle/manifest.json": 1}
            sorted_payloads = sorted(
                file_payloads,
                key=lambda item: (priority.get(item[0], 2), item[0]),
            )
            for path, payload in sorted_payloads:
                zf.writestr(path, payload)

        return zip_buf.getvalue()

    def _assemble_report_formats(self, add_file: Any) -> None:
        """Render and capture requested report documents once."""
        detail = self.options.detail
        style = self.options.style
        title = self.options.title
        include_figures = self.options.include_figures

        target_obj = (
            self.report
            if self.report is not None
            else (self.analysis if self.analysis is not None else self.view)
        )

        for fmt in self.formats:
            if fmt == "html":
                if self.report is not None:
                    html_str = self.report.to_html(
                        detail=detail,
                        style=style,
                        title=title,
                    )
                else:
                    from ..presentation import to_html

                    html_str = to_html(target_obj, detail=detail, style=style, title=title)
                add_file(
                    "pyautostat_bundle/report/report.html",
                    "human_readable_report",
                    "html",
                    html_str.encode("utf-8"),
                )

            elif fmt == "interactive_html":
                if self.report is not None:
                    ihtml_str = self.report.to_interactive_html(
                        detail=detail,
                        style=style,
                        title=title,
                        include_figures=include_figures,
                    )
                else:
                    from ..presentation import to_interactive_html

                    ihtml_str = to_interactive_html(
                        target_obj,
                        detail=detail,
                        style=style,
                        title=title,
                        include_figures=include_figures,
                    )
                add_file(
                    "pyautostat_bundle/report/report_interactive.html",
                    "interactive_report",
                    "interactive_html",
                    ihtml_str.encode("utf-8"),
                )

            elif fmt == "pdf":
                if self.report is not None:
                    pdf_bytes = self.report.to_pdf(
                        detail=detail,
                        style=style,
                        title=title,
                        include_figures=include_figures,
                        page_size=self.options.page_size,
                        landscape=self.options.landscape,
                        page_numbers=self.options.page_numbers,
                    )
                else:
                    from ..presentation import to_pdf

                    pdf_bytes = to_pdf(
                        target_obj,
                        detail=detail,
                        style=style,
                        title=title,
                        include_figures=include_figures,
                        page_size=self.options.page_size,
                        landscape=self.options.landscape,
                        page_numbers=self.options.page_numbers,
                    )
                add_file(
                    "pyautostat_bundle/report/report.pdf", "human_readable_report", "pdf", pdf_bytes
                )

            elif fmt == "docx":
                if self.report is not None:
                    docx_bytes = self.report.to_docx(
                        detail=detail,
                        style=style,
                        title=title,
                        page_size=self.options.page_size,
                        landscape=self.options.landscape,
                        page_numbers=self.options.page_numbers,
                    )
                else:
                    from ..presentation import to_docx

                    docx_bytes = to_docx(
                        target_obj,
                        detail=detail,
                        style=style,
                        title=title,
                        page_size=self.options.page_size,
                        landscape=self.options.landscape,
                        page_numbers=self.options.page_numbers,
                    )
                add_file(
                    "pyautostat_bundle/report/report.docx", "editable_report", "docx", docx_bytes
                )

            elif fmt == "json":
                if self.report is not None:
                    json_bytes = self.report.to_json().encode("utf-8")
                    add_file(
                        "pyautostat_bundle/data/report.json",
                        "canonical_report_data",
                        "json",
                        json_bytes,
                    )
                elif self.analysis is not None:
                    json_bytes = json.dumps(
                        self.analysis.to_dict(), indent=2, ensure_ascii=False
                    ).encode("utf-8")
                    add_file(
                        "pyautostat_bundle/data/analysis.json",
                        "canonical_analysis_data",
                        "json",
                        json_bytes,
                    )

            elif fmt == "markdown" and self.report is not None:
                md_bytes = self.report.to_markdown().encode("utf-8")
                add_file(
                    "pyautostat_bundle/report/report.md", "markdown_report", "markdown", md_bytes
                )

            elif fmt == "latex" and self.report is not None:
                tex_bytes = self.report.to_latex().encode("utf-8")
                add_file("pyautostat_bundle/report/report.tex", "latex_report", "latex", tex_bytes)

    def _assemble_provenance(self, add_file: Any) -> None:
        """Assemble already-recorded execution provenance without recalculation."""
        # 1. Authoritative analysis dictionary
        if self.analysis is not None:
            an_dict = self.analysis.to_dict()
            an_bytes = json.dumps(an_dict, indent=2, ensure_ascii=False).encode("utf-8")
            add_file(
                "pyautostat_bundle/provenance/analysis.json", "analysis_record", "json", an_bytes
            )
        elif self.report is not None:
            source_res = getattr(self.report, "_source_result", None)
            if source_res is not None and hasattr(source_res, "to_dict"):
                an_dict = source_res.to_dict()
                an_bytes = json.dumps(an_dict, indent=2, ensure_ascii=False).encode("utf-8")
                add_file(
                    "pyautostat_bundle/provenance/analysis.json",
                    "analysis_record",
                    "json",
                    an_bytes,
                )

        # 2. Reproducibility record
        if self.reproducibility is not None:
            rep_dict = (
                self.reproducibility.to_dict()
                if hasattr(self.reproducibility, "to_dict")
                else dict(self.reproducibility)
            )
            rep_bytes = json.dumps(rep_dict, indent=2, ensure_ascii=False).encode("utf-8")
            add_file(
                "pyautostat_bundle/provenance/reproducibility.json",
                "reproducibility_record",
                "json",
                rep_bytes,
            )

        # 3. Audit trail
        if self.audit is not None:
            aud_dict = self.audit.to_dict() if hasattr(self.audit, "to_dict") else dict(self.audit)
            aud_bytes = json.dumps(aud_dict, indent=2, ensure_ascii=False).encode("utf-8")
            add_file("pyautostat_bundle/provenance/audit.json", "audit_record", "json", aud_bytes)

        # 4. Session snapshot
        if self.session is not None:
            sess_dict = (
                self.session.to_dict() if hasattr(self.session, "to_dict") else dict(self.session)
            )
            sess_bytes = json.dumps(sess_dict, indent=2, ensure_ascii=False).encode("utf-8")
            add_file(
                "pyautostat_bundle/provenance/session.json", "session_record", "json", sess_bytes
            )
